version: '3.8'
services:
  dev-database:
    image: postgres:17.6
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    networks:
      - base-nestjs-networks
networks:
  base-nestjs-networks:
    driver: bridge

# docker compose up -d
# -d: background mode