export const ErrorCode = {
  // Auth
  AUTH_ERROR_PASSWORD_MISMATCH: 'ERROR-AUTH-0000',
  AUTH_ERROR_OTP_INVALID_OR_EXPIRED: 'ERROR-AUTH-0001',
  AUTH_ERROR_UNAUTHORIZED: 'ERROR-AUTH-0002',

  // Account
  ACCOUNT_ERROR_NOT_FOUND: 'ERROR-ACCOUNT-0000',
  ACCOUNT_ERROR_EMAIL_EXISTED: 'ERROR-ACCOUNT-0001',
  ACCOUNT_ERROR_INVALID_PASSWORD: 'ERROR-ACCOUNT-0002',
  ACCOUNT_ERROR_PHONE_EXISTED: 'ERROR-ACCOUNT-0003',
  ACCOUNT_ERROR_NOT_ALLOW_DELETE: 'ERROR-ACCOUNT-0004',
  ACCOUNT_ERROR_EMAIL_INVALID: 'ERROR-ACCOUNT-0005',

  // Category
  CATEGORY_ERROR_NOT_FOUND: 'ERROR-CATEGORY-0000',
  CATEGORY_ERROR_NAME_EXISTED: 'ERROR-CATEGORY-0001',
  CATEGORY_ERROR_INVALID_REQUEST: 'ERROR_CATEGORY_0002',
  CATEGORY_ERROR_IN_USE: 'ERROR_CATEGORY_0003',

  // Permission
  PERMISSION_ERROR_NOT_FOUND: 'ERROR-PERMISSION-0000',
  PERMISSION_ERROR_NAME_EXISTS: 'ERROR-PERMISSION-0001',
  PERMISSION_ERROR_CODE_EXISTS: 'ERROR-PERMISSION-0002',

  // Group
  GROUP_ERROR_NOT_FOUND: 'ERROR-GROUP-0000',
  GROUP_ERROR_NAME_EXISTS: 'ERROR-GROUP-0001',
  GROUP_ERROR_IN_USED: 'ERROR-GROUP-0002',

  // Product
  PRODUCT_ERROR_NOT_FOUND: 'ERROR-PRODUCT-0000',

  // File
  FILE_ERROR_KIND_REQUIRED: 'ERROR-FILE-0000',
  FILE_ERROR_KIND_INVALID: 'ERROR-FILE-0001',

  // Product image
  PRODUCT_IMAGE_ERROR_NOT_FOUND: 'PRODUCT_IMAGE_ERROR_NOT_FOUND',
  PRODUCT_IMAGE_ERROR_INVALID_REQUEST: 'PRODUCT_IMAGE_ERROR_INVALID_REQUEST',

  // Permission Group
  PERMISSION_GROUP_ERROR_NOT_FOUND: 'ERROR-PERMISSION-GROUP-0000',
  PERMISSION_GROUP_ERROR_NAME_EXISTS: 'ERROR-PERMISSION-GROUP-0001',

  // Cart
  CART_ERROR_NOT_FOUND: 'ERROR-CART-0000',

  // Cart Item
  CART_ITEM_ERROR_NOT_FOUND: 'ERROR-CART-ITEM-0000',

  //Publisher
  PUBLISHER_ERROR_NOT_FOUND: 'ERROR_PUBLISHER_NOT_FOUND_0000',

  // Product Variant
  PRODUCT_VARIANT_ERROR_NOT_FOUND: 'ERROR-PRODUCT-VARIANT-0000',
  PRODUCT_VARIANT_ERROR_EXISTED: 'ERROR-PRODUCT-VARIANT-0001',

  // Contributor
  CONTRIBUTOR_ERROR_NOT_FOUND: 'ERROR_CONTRIBUTOR_NOT_FOUND_0000',
  CONTRIBUTOR_ERROR_DELETED: 'ERROR-CONTRIBUTOR-DELETE-0001'
} as const;
