export const ErrorCode = {
  // Auth
  AUTH_ERROR_PASSWORD_MISMATCH: 'ERROR-AUTH-0000',
  AUTH_ERROR_OTP_INVALID_OR_EXPIRED: 'ERROR-AUTH-0001',

  // Account
  ACCOUNT_ERROR_NOT_FOUND: 'ERROR-ACCOUNT-0000',
  ACCOUNT_ERROR_EMAIL_EXISTED: 'ERROR-ACCOUNT-0001',
  ACCOUNT_ERROR_INVALID_PASSWORD: 'ERROR-ACCOUNT-0002',
  ACCOUNT_ERROR_PHONE_EXISTED: 'ERROR-ACCOUNT-0003',

  // Category
  CATEGORY_ERROR_NOT_FOUND: 'ERROR-CATEGORY-0000',
  CATEGORY_ERROR_NAME_EXISTED: 'ERROR-CATEGORY-0001',
} as const;
